timezone: Asia/Shanghai
ai:
  api_base: ''
  api_key: sk-e467146b9f954be2aad5f2d955451bac
  batch_interval: 2
  batch_size: 200
  max_tokens: 5000
  min_score: 0.7
  model: deepseek/deepseek-chat
  summary_enabled: true
  timeout: 120
cron_schedule: '*/30 * * * *'
miniflux_api_key: 96551dff06c68bcbeb404ef90f4023151af2dfcbb457794aae2ae2080aa69dce
miniflux_url: http://miniflux:8080
notification:
  batch_interval: 2
  dingtalk_webhook_url: ''
  email_from: ''
  email_password: ''
  email_to: ''
  feishu_webhook_url: ''
  slack_webhook_url: ''
  telegram_bot_token: ''
  telegram_chat_id: ''
obsidian_vault_path: /obsidian
output_dir: /app/output
platforms:
- toutiao
- baidu
- wallstreetcn-hot
- thepaper
- bilibili-hot-search
- cls-hot
- ifeng
- tieba
- weibo
- douyin
- zhihu
rsshub_url: http://rsshub:1200
